version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'nBVvH9llR7ODrmQ0iCUHJ4pI'
      ACCEPT_EULA: 'Y'
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mssql_data:
  redis-data:
    driver: local
