BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Client] ALTER COLUMN [StartDate] DATETIME2 NULL;
ALTER TABLE [dbo].[Client] ADD CONSTRAINT [Client_EndDate_df] DEFAULT '2050-12-31 23:59:59 +00:00' FOR [EndDate];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
