BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Permission] ALTER COLUMN [EndDate] DATETIME2 NULL;

-- AlterTable
ALTER TABLE [dbo].[Profile] ALTER COLUMN [EndDate] DATETIME2 NULL;

-- AlterTable
ALTER TABLE [dbo].[Role] ALTER COLUMN [EndDate] DATETIME2 NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
