import { PrismaClient } from '@prisma/client';
import logger from '../../libs/logger';

const prisma = new PrismaClient();

const questions = [
  {
    id: 1,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'AV?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 1,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 2,
    questionCategory: 'Meeting Rooms',
    questionType: 'Checkbox',
    question: 'What is the table setup in the room?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 2,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 3,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Does the rooms provided have 4 SOLID walls and a door?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 3,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 4,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question:
      'Are the windows covered for the rooms? - If so, can they be blacked out for complete privacy?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 4,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 5,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Is the room wheel-chair accessible?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 5,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 6,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Are you able to provide a picture of the room?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 6,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 7,
    questionCategory: 'Meeting Rooms',
    questionType: 'File Upload',
    question: 'Upload',
    isActive: true,
    parentQuestion: 'Are you able to provide a picture of the room?',
    DisplayOrder: 7,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 8,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Is there a Room Rental Fee for this room?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 8,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 9,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Do you add tax to the Room Rental?',
    isActive: true,
    parentQuestion: 'Is there a Room Rental Fee for this room?',
    DisplayOrder: 9,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 10,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Do you add gratuity to your room rental?',
    isActive: true,
    parentQuestion: 'Is there a Room Rental Fee for this room?',
    DisplayOrder: 10,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 11,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Is the room available for AV set-up at least 1 hour prior?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 11,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 12,
    questionCategory: 'Meeting Rooms',
    questionType: 'Radio',
    question: 'Is there a phone in the room?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 12,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 13,
    questionCategory: 'Meeting Rooms',
    questionType: 'Textarea',
    question: 'Comments',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 13,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 14,
    questionCategory: 'Venue Details',
    questionType: 'Radio',
    question: 'Is the venue closed on any specific days?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 1,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 15,
    questionCategory: 'Venue Details',
    questionType: 'Checkbox',
    question: 'Please select which days will the venue be closed',
    isActive: true,
    parentQuestion: 'Is the venue closed on any specific days?',
    DisplayOrder: 2,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 16,
    questionCategory: 'Venue Details',
    questionType: 'Radio',
    question:
      'Is the Venue located in a golf club/resort, spa, casino or winery?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 3,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 17,
    questionCategory: 'Venue Details',
    questionType: 'Radio',
    question: 'Are any other Pharma companies booked on this date?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 4,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 18,
    questionCategory: 'Venue Details',
    questionType: 'Textbox',
    question: 'Please advise which company',
    isActive: true,
    parentQuestion: 'Are any other Pharma companies booked on this date?',
    DisplayOrder: 5,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 19,
    questionCategory: 'Venue Details',
    questionType: 'Radio',
    question: 'Is Parking available? (Valet/Yes or Self/No)',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 6,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 20,
    questionCategory: 'Venue Details',
    questionType: 'Textbox',
    question: 'Please indicate cost or NA if no cost',
    isActive: true,
    parentQuestion: 'Is Parking available? (Valet/Yes or Self/No)',
    DisplayOrder: 7,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 21,
    questionCategory: 'Venue Details',
    questionType: 'Textbox',
    question: 'DBA',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 8,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 22,
    questionCategory: 'Venue Details',
    questionType: 'Textarea',
    question: 'Comments',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 9,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 23,
    questionCategory: 'Audio Visual',
    questionType: 'Radio',
    question: 'Do you have wireless or hardwire internet',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 1,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 24,
    questionCategory: 'Audio Visual',
    questionType: 'Radio',
    question: 'Do you charge Tax on the AV cost?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 2,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 25,
    questionCategory: 'Audio Visual',
    questionType: 'Textbox',
    question: 'Percentage of Tax',
    isActive: true,
    parentQuestion: 'Do you charge Tax on the AV cost?',
    DisplayOrder: 3,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 26,
    questionCategory: 'Audio Visual',
    questionType: 'Radio',
    question: 'Do you charge gratuity on the AV cost?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 4,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 27,
    questionCategory: 'Audio Visual',
    questionType: 'Textbox',
    question: 'Percentage of Gratuity',
    isActive: true,
    parentQuestion: 'Do you charge gratuity on the AV cost?',
    DisplayOrder: 5,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 28,
    questionCategory: 'Audio Visual',
    questionType: 'Radio',
    question: 'Does the Venue provide any cords? (ex. HDMI, VGA, etc)',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 6,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 29,
    questionCategory: 'Audio Visual',
    questionType: 'Radio',
    question: 'Do you allow outside A/V vendors?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 7,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 30,
    questionCategory: 'Audio Visual',
    questionType: 'Textarea',
    question: 'Comments',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 8,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 31,
    questionCategory: 'Menu and Cost',
    questionType: 'Radio',
    question:
      'Are you able to provide a separate receipt for F&B, AV  or unmet min/room fee?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 1,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 32,
    questionCategory: 'Menu and Cost',
    questionType: 'Radio',
    question: 'Do you have Pre-set menu options?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 2,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 33,
    questionCategory: 'Menu and Cost',
    questionType: 'File Upload',
    question: 'Upload',
    isActive: true,
    parentQuestion: 'Do you have Pre-set menu options?',
    DisplayOrder: 3,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 34,
    questionCategory: 'Menu and Cost',
    questionType: 'Textbox',
    question: 'Please provide your average per-person meal costs',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 4,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 35,
    questionCategory: 'Menu and Cost',
    questionType: 'Textbox',
    question: 'What is your tax %?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 5,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 36,
    questionCategory: 'Menu and Cost',
    questionType: 'Textbox',
    question: 'What is your Gratuity %?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 6,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 37,
    questionCategory: 'Menu and Cost',
    questionType: 'Textarea',
    question: 'Comments',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 7,
    createdBy: 1,
    updatedBy: 1,
  },

  {
    id: 38,
    questionCategory: 'Contract and Policies',
    questionType: 'Radio',
    question: 'Do you have a contract we need to sign?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 1,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 39,
    questionCategory: 'Contract and Policies',
    questionType: 'File Upload',
    question: 'Upload your contract files',
    isActive: true,
    parentQuestion: 'Do you have a contract we need to sign?',
    DisplayOrder: 2,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 40,
    questionCategory: 'Contract and Policies',
    questionType: 'Radio',
    question: 'Will you sign our contract?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 3,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 41,
    questionCategory: 'Contract and Policies',
    questionType: 'Textarea',
    question: 'What is your cancellation policy?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 4,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 42,
    questionCategory: 'Contract and Policies',
    questionType: 'Radio',
    question: 'Do you charge for Final head count?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 5,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 43,
    questionCategory: 'Contract and Policies',
    questionType: 'Radio',
    question: 'Do you accept credit card via email/fax/phone?',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 6,
    createdBy: 1,
    updatedBy: 1,
  },
  {
    id: 44,
    questionCategory: 'Contract and Policies',
    questionType: 'Textarea',
    question: 'Comments',
    isActive: true,
    parentQuestion: null,
    DisplayOrder: 7,
    createdBy: 1,
    updatedBy: 1,
  },
];

async function getCategoryIdByName(name: string) {
  const category = await prisma.questionCategory.findFirst({ where: { name } });
  return category?.id || null;
}

async function getTypeIdByName(name: string) {
  const type = await prisma.questionType.findFirst({ where: { name } });
  return type?.id || null;
}

async function getParentQuestionIdByQuestion(
  questionText: string | null,
  questionCategoryId: number,
) {
  if (!questionText || questionText === null) return null;
  const parent = await prisma.question.findFirst({
    where: { question: questionText, questionCategoryId },
  });
  return parent?.id || null;
}

async function loadQuestionData() {
  try {
    logger.info('Seeding QuestionData...');

    for (const data of questions) {
      const questionCategoryId = await getCategoryIdByName(
        data.questionCategory,
      );
      if (!questionCategoryId) {
        logger.warn(`Skipping question ID ${data.id} due to missing category.`);
        continue;
      }
      const [questionTypeId, parentQuestionId] = await Promise.all([
        getTypeIdByName(data.questionType),
        getParentQuestionIdByQuestion(data.parentQuestion, questionCategoryId),
      ]);

      if (!questionTypeId) {
        logger.warn(`Skipping question ID ${data.id} due to missing type.`);
        continue;
      }

      await prisma.question.upsert({
        where: { id: data.id },
        update: {},
        create: {
          questionCategoryId,
          questionTypeId,
          question: data.question,
          isActive: data.isActive,
          parentQuestionId,
          displayOrder: data.DisplayOrder,
          createdBy: data.createdBy,
          updatedBy: data.updatedBy,
        },
      });
    }

    logger.info('QuestionData seeded successfully.');
  } catch (error) {
    logger.error('Error in inserting data:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

loadQuestionData();
