BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[TableRelation] (
    [id] INT NOT NULL IDENTITY(1,1),
    [CurrentTable] NVARCHAR(1000) NOT NULL,
    [FieldName] NVARCHAR(1000) NOT NULL,
    [RelationTable] NVARCHAR(1000) NOT NULL,
    [MasterTable] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [TableRelation_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
