BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[ProfilePhoneInfo] ALTER COLUMN [PhoneNumber] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[ProfilePhoneInfo] ALTER COLUMN [PhoneNumberExtension] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[ProfilePhoneInfo] ALTER COLUMN [FaxNumber] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
