BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Role] ADD [StatusId] INT NOT NULL CONSTRAINT [Role_StatusId_df] DEFAULT 1;

-- AddForeignKey
ALTER TABLE [dbo].[Role] ADD CONSTRAINT [Role_StatusId_fkey] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[Status]([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
